language: csharp
solution: Universe.sln
mono:
  - latest
script:
  - ./runprebuild.sh
  - xbuild /p:Configuration=Release Universe.sln
notifications:
  irc:
    channels:
      - "chat.freenode.net#galaxyfutures"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
